### ISSUE TITLE
Player 2 isnt showing up

### ISSUE THREAD

**Issue by Ashcuifer04** [ShadowTheHedgehogHacking/2P-ShdTH#6]
Ive been adjusting the gecko codes and still player 2 doesnt show up when i select a level. Also get this warning (0x000000, PC = 0x80002634, 0x80002638, 0x8000264) idk whats that about
![image](https://user-images.githubusercontent.com/118433321/202403228-5dde16b9-7469-4dbb-a933-8c92ba9a137c.png)
Its looks like this so far , not sure if im missing files cuz i followed the guide 3 times ..... anyways this mod looks amazing and hope to play this with my little cousins when it gets fixed!

**Comment by dreamsyntax** [comment]
Hi, this error means the DOL modification is not present, and judging by the screenshot something is wrong with the aspect ratio as well.

Please use the release:
https://github.com/ShadowTheHedgehogHacking/2P-ShdTH/releases/tag/2.3beta

Files rather than the raw repo files, as they do not contain the DOL modification.
(Specifically:
`ISO_EDITS\sys\main.dol` is what you need)

**Comment by Ashcuifer04** [comment]
works now! thanks so much

**Comment by dreamsyntax** [comment]
Pinning incase others run into this
