### ISSUE TITLE
Solved: 2nd Screen Appears but Player 2 Does Not Spawn

### ISSUE THREAD

**Issue by Cooldood72** [ShadowTheHedgehogHacking/2P-ShdTH#9]
Im on nintendont on my wii u. Everytime i load the game up, none of the changes are present until i load a level then the second screen is present but no player 2. I tried loading a 2p match then going back into the same level (westopolis) and the camera is in a different spot but still no player 2. the 100% save works and so does the code manager settings, just not player 2. I've tried following the tutorial on github and youtube, but it still won't work. I saw the other person with a similar issue but on dolphin so I dont know if there is a similar fix or not. I'm using the latest version btw.

**Comment by dreamsyntax** [comment]
Hi, the behavior you describe means Gecko codes are working but you are missing the ROM patches (ISO patch)

It is necessary to use the release version and patch the ISO. Cloning the repo directly instead of using the release can result in this. This means download either v2.3b from Releases Tab or v2.2.


Double check the ISO you copied to your SD/USB is the one you built in Dolphin, and not the unmodified ISO.

**Comment by Cooldood72** [comment]
Thanks for responding! It works perfectly now.
